import Foundation
import ViewSchema

/// A property wrapper that tracks observable property access for expression capture.
///
/// `ObservableProperty` is the magic that enables seamless SwiftUI syntax in ServerUI.
/// It allows properties to behave like normal values while also being captured as
/// bindings in Text interpolation.
///
/// ## How It Works
///
/// The `@RemotelyObservable` macro transforms properties into `ObservableProperty` wrappers:
///
/// ```swift
/// @RemotelyObservable
/// class Profile {
///     var name = "John"  // Becomes ObservableProperty<String>
/// }
///
/// // All of these "just work":
/// Text("Hello \(profile.name)!")      // ← Captured as expression
/// Text(profile.name)                  // ← Captured as expression
/// TextField("Name", text: $profile.name)  // ← Works as Binding
/// let x: String = profile.name        // ← Acts like String
/// ```
///
/// ## Magic Tricks
///
/// 1. **Acts like the wrapped value**: Implicit conversion to `Value`
/// 2. **Captures in Text interpolation**: Custom `appendInterpolation`
/// 3. **Works with `$`**: `projectedValue` returns `Binding`
/// 4. **Type-safe**: Full compiler checking
///
/// ## Implementation Note
///
/// This is generated by the `@RemotelyObservable` macro. You typically don't
/// create `ObservableProperty` instances manually.
///
/// - SeeAlso: `@RemotelyObservable`, `Expression`, `Text.StringInterpolation`
@propertyWrapper
public struct ObservableProperty<Value: Sendable>: Sendable {
    /// The cache key for this property (e.g., "objectID::propertyName")
    public let key: String
    
    /// The current value of the property
    public let value: Value
    
    /// Creates an observable property.
    ///
    /// - Parameters:
    ///   - key: The cache key (e.g., "objectID::propertyName")
    ///   - value: The current value
    public init(key: String, value: Value) {
        self.key = key
        self.value = value
    }
    
    /// The wrapped value - allows implicit conversion to the underlying type.
    ///
    /// This makes the property behave like a normal value in most contexts:
    /// ```swift
    /// let name: String = profile.name  // ← Gets the actual String value
    /// ```
    public var wrappedValue: Value {
        get { value }
        set { /* This setter is here for property wrapper semantics, but won't be called */ }
    }
    
    /// The projected value - enables `$property` syntax for bindings.
    ///
    /// This allows the property to work with TextField and other binding-based components:
    /// ```swift
    /// TextField("Name", text: $profile.name)  // ← Works!
    /// ```
    public var projectedValue: Binding<Value> {
        // Create a binding using the key
        // The actual value will be read from StateStore/ObservableStore
        Binding(key: key, initialValue: value)
    }
}

// MARK: - String Conversion

extension ObservableProperty: CustomStringConvertible {
    /// String representation for direct Text usage.
    ///
    /// This enables patterns like:
    /// ```swift
    /// Text(profile.name)  // ← Converts to String automatically
    /// ```
    public var description: String {
        String(describing: value)
    }
}

// MARK: - Equatable & Hashable

extension ObservableProperty: Equatable where Value: Equatable {
    public static func == (lhs: ObservableProperty<Value>, rhs: ObservableProperty<Value>) -> Bool {
        lhs.key == rhs.key && lhs.value == rhs.value
    }
}

extension ObservableProperty: Hashable where Value: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(value)
    }
}

// MARK: - Helper for Binding Creation

extension Binding where Value: Sendable {
    /// Creates a binding from a state key and initial value.
    ///
    /// This is used internally by `ObservableProperty` to create bindings
    /// for TextField and other components.
    ///
    /// - Parameters:
    ///   - key: The state key
    ///   - initialValue: The initial value (used for fallback)
    fileprivate init(key: String, initialValue: Value) {
        // Store the key in the binding
        // The actual get/set will use StateStore/ObservableStore
        self.init(
            stateKey: key,
            get: { initialValue },  // Fallback value
            set: { _ in }  // Set is handled by the binding system
        )
    }
}

